export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const USER_SIGNED_OUT = 'USER_SIGNED_OUT'
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS'

export const SET_SESSION_ERROR = 'SET_SESSION_ERROR'
export const CLEAR_SESSION_ERROR = 'CLEAR_SESSION_ERROR'

export const SET_CHANGE_PASSWORD_ERRORS = 'SET_CHANGE_PASSWORD_ERRORS'
export const CLEAR_CHANGE_PASSWORD_ERRORS = 'CLEAR_CHANGE_PASSWORD_ERRORS'

export const SET_REGISTRATIONS_ERRORS = 'SET_REGISTRATIONS_ERRORS'
export const CLEAR_REGISTRATIONS_ERRORS = 'CLEAR_REGISTRATIONS_ERRORS'
